---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-secret
  namespace: default
spec:
  encryptedData:
    database-url: AgCxw4dQZ2bayfWzHVSNkPQheSJufzpVlqx8UYgVFr2KjqwyigNCPisoQot/6EI7IZ87b58zSqs5Umjnrq7rjeiyq4yYTs9PP+9+tuH8J0/oBgYkBQpENUVxgc8CQ9OoJ1zWy2uBip97iMzkCsX84Et0KynJ5if0+5K5/r9wMP8ScRuocRGzZRPJD36UJwutTG6/5E926dTFztFNxFnab6Fn3jT/8wlwmajXih0UBQ4UAN0WNtqC50TEE7rH9rWlY6L3+80Mzf7gdXMhkkVSYssZjR+ir9K8w4orsibILjkxICpmCmVhuLhhVDH3AFDg1G16SItqIW/RkiEuiqptkVcBvrgnF/c9Bu5mQpoVpPAMW6l7MSzLi7E8ezOGU9iDBMwbbChXjIO9koWZkdYy5XN4fWnBpnhAn8/quwjyjx7YnBlloCBq1oIavZSw3im1MPfYEv/F7UrZCr5FXKBXL5ul9X+dAEHDE4WbzwUJNRly2Y1P1qXaVrqHqOiMmdqNEQWRnddsEkCIKIz86Kr0QBYkpDK6C+s+e4lg8X1qSVc0js6uHYTVq6OaWjevKQKszp1IHmYe0i3NoM5coToQab/0jvtx+VajlV8vMRMB20VZRVeeth9qh6csfFmq+qrb48qqTK0us7alTqHc5XEJ8td2O7q7i7j6UneEHzwk6m/Jn1c3E6WNSN66kjNdvqCAC/bJ8iZJhpQ/eZvZOVphkgPw6hS4UgDxACXIhTXlhONlX2ERDveIgCA8JAdj+sFo+18k3MLSpiI=
  template:
    metadata:
      name: api-secret
      namespace: default
