---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: default
spec:
  encryptedData:
    password: AgBQ5gKQ1WiVRQaXHwhl9hb/8h/FK5XS+vTfHAKNP+QXqOMk7lBh7cDS/bPDaOUVx7k8hivDNT/BMJ/LmyDrl8ZBJEJa34HugJNN8z+Wdpd61llgZ08eM2aA9SMhTlScINji2lbpJw2IY7fFCXjxRIFBFmoZi1OGfZzuTkNEm8fzhXovx9lP/zzgbLtO1CXHuabISTd8KSlGbdoumRXJ5EqAEqyO+k0EwhYN0CW7g7TZtoPY4yQn0676VtTYt3GXyD0SB/7SYxD4hjN/ZmAtB9Ybn3Fr1wGf0f8K0uZtTm7D+CCM+1lWXsyt5FY26AAZtYvNzcY4L3X941Cg6W1Eh5giAW7fRO24482Q8TFd8tqrJzzXh+fz8mw2S/ejDXR34HEmLjGn/mJ3zIQZ/U9nwGj63iGbRu1XzjAisvGbSIbzMQOeDE8+gG1B3fIdsEHdMJj4BVUy+YCXPYkPpOOXBqJNa5NfeoGueghIufzwePVz/AoIri89fxnfVGjWyhGsZIx+zysvf0zn/XCSTP+A/Jv63NVKkQgzXq4xjU4lq5fEN+CCJXSa7dlvLPphfGp7ro0kwLWe92ie/UFo2kBTmJlQZmM7AAlt9sx4+XPq1WoPUkHUlyzB7ANHm2fh/1cy5avy7UWjF48RST1BRtognfyqTFrDEmlWkWQ7fuohlywj7IxLBgReiUP93dsTzjlOFpCjJ5agZQ/URg==
  template:
    metadata:
      name: db-secret
      namespace: default
