---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: default
spec:
  encryptedData:
    password: AgCa/IWOqp6bkC5wVtRzl3r40bFr6qIUA6D9SzexpmJBpYK+Z5UnXmPa+zdTdQ0D+aW7R1HyjMlM6QP555i+3KSM5KJLLelV/U2S8bbQXaUHhIr1WawmV58YZqWU50dcarIdUTzqyxnNdO/sZbVSlJc/18Bby0pgL6/E2wwotLNa1Lxs5wx5fM3IsJs+nfVLroj6S5LapT2DLzlFs/9XreC2ckr+8RCGWoWXO4qSx4NjsIn5O+5j4YDyj32Ntt0bdH7Go7Y4Ki4ZZA8VEvxAZ0FN5/x4AK6SHt7iHFaqTnX41TPOQ/nTUjsnN0h1cHrPJbNlvpThX14SyliVUBETghghvKx+tgRvEP5ljsLpnk0VslRn+6RdgALTT4SWpNu1LF8FnqPKYB9Sj9a/VnoqydnUhqrUw+czRRR8H5srRLIkPLmY7AhBBCmPozhmRx8cp8XUbis9osZFL8fhhQeStyPT9bVHJ+osimpuduEg8uiZC6m5Ak/lRDL8HkHpVGZtkz10loAHH4Va+bPdYT2l32VYcrAP4sVaUkCipVXiYnObaHaga5NeEBJr6RDvTujoDaERVeQHQAQlA9vhB1pr/3jq4MdbL3KAMiK9oEURTudiLzIZIqPc/Gfyy6YwjwV0lC7bQbyAgS//oUARSdkVv2AkASVWP6J4hPy2429WYBJDYCD4pfx6Nz4noFbPJNGB8pGAFdowsZKbKle/hYcLwPU=
  template:
    metadata:
      name: db-secret
      namespace: default
