---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: default
spec:
  encryptedData:
    password: AgCkhpR+Q47B2W6UNNb4Rdsf14oPO1t6dGFwSDec8jR12lCmlYEnMQXR2Oc+iORvQLyYXKeOFMjvqR0u2VK89w5gaq3bwiWZfOPUvtoKRb+El5wO704x+H9ZNHeCMs9VZGfvKaI87fq+o2e7DT9lcsw/4Vo/UJr8s4RcR2n3dMBIA+3VSehtap8dGHjHfAhVayIa9pPzi23vdD59FGszMZ3XvQT1A9ZgEjRnUnSIa85laWym+F9MF2HvgpdD1wWlsNtCa16ssyHsAwBwyKUfP3KPf4gN6ng5AI9NtjsB6UoS0M7X4kx+wAzoDP7UjYmuFha0cmJgFhdJ1sd2asFX/l0GX+kQ3QfzldIRyFfRrsT9/juwwMD0dy5K0fATpAq1fFt5kbA+WyZDPgdUqV89EOSdNspWCvOKAeQvxRLJcle0uGczOHb+5U4nzediLohip89NeboBwOUkEvREKJX0rSbC15BkS5AlmhOoDzpfXxA1Xn26w600VbpLWPFoHt8cTzJWButihlyZjPAyAm5l8R91B6nTZM7dCCXDejSiQanSkaKQO65hWIRMx+pvHvK2Wp7eD44p1XuVyzpiVQLOIeHrcM3ofC7VyOwnR3lndqUt1WBQbwD+GiqTygREr1iiaWE6NUv5enrdZ+3LqqFAWUyuXPdGnAAtyHauzoVdo+cQeVoe+w+blgMF+Oj47k+776gJTr8AX635hwKpRuv9yw==
  template:
    metadata:
      name: db-secret
      namespace: default
